### ISSUE TITLE
Task 3: In the people section, images become black  squares

### ISSUE THREAD

**Issue by patrick-mzaaber** [oibeirut/oib_website#8] opened 2020-10-19 08:54 UTC
(https://www.orient-institut.org/people/fellows/), Upon hovering above images on the same page, they become over-saturated. (This matter is occurring as well with the events section – poster shown on the original page before being maximized; “The “News and Publications” on our main page is facing the same troubles as well – Publications logos are pixelated/not  clear).

**Comment by tillgrallert** [comment] 2020-10-19 09:38
I would say this is a duplicate of #7

**Closed by tillgrallert** 2020-10-19 09:38 UTC
Labels: backend, bug, frontend, images, question
