### ISSUE TITLE
Task 1: Automated cropping distorts images

### ISSUE THREAD

**Issue by patrick-mzaaber** [oibeirut/oib_website#6] opened 2020-10-19 08:47 UTC
The website applies automated cropping to images for the homepage tiles without respecting the input side- ratio. Thus, rectangular images are distorted into square shapes. As long as this isn't solved, we have to make sure that all imagery adheres to the correct ratio before upload. (Filtering of images? aggressive contrast and color filtering – max width of 300  pixels?)

[OrientInstitut 2020.docx](https://github.com/oibeirut/oib_website/files/5400374/OrientInstitut.2020.docx)

**Comment by tillgrallert** [comment] 2020-10-19 09:36
Duplicate of issue  #3

**Closed by tillgrallert** 2020-10-19 09:36 UTC
Labels: images
