### ISSUE TITLE
Task 2: Everything is too dark and  over-saturated

### ISSUE THREAD

**Issue by patrick-mzaaber** [oibeirut/oib_website#7] opened 2020-10-19 08:52 UTC
There is an automatic filter applied to all images. Currently, I don't know whether this occurs upon upload or during rendering. However, the effect is devastating.

Comments: Can you show us example links of the pages where you have put this effect? Normally such an effect is not automatically applied, if you provide us links only we can debug the problem and propose a solution for it.

[OrientInstitut 2020.docx](https://github.com/oibeirut/oib_website/files/5400414/OrientInstitut.2020.docx)

**Comment by tillgrallert** [comment] 2020-10-19 09:37
This is a duplicate of #2

**Closed by tillgrallert** 2020-10-19 09:37 UTC
Labels: backend, bug, frontend, images, question
